name: deploy

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: theayarayarovich
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: theayarayarovich/fastapi_pipelined:latest,theayarayarovich/fastapi_pipelined:${{ github.ref_name }}